### ISSUE TITLE
Double Write of SeqId?

### ISSUE THREAD

**Issue by kbahr** [netifi-proteus/proteus-java#1]
https://github.com/netifi-proteus/proteus-java/blob/2d287cf0333fe2b175f448f1655fbe8e086fcd2b/frames/src/main/java/io/netifi/proteus/frames/AuthenticationResponseFlyweight.java#L35

Isn't the sequence ID written as part of the header? Is this redundant or is there something I missed on the authentication response frame such that it needs it twice?

**Comment by robertroeser** [comment]
we removed seq id
