### ISSUE TITLE
Compilation issues when using Spring Boot

### ISSUE THREAD

**Issue by gregwhitaker** [netifi-proteus/proteus-java#5]
## Issue
Currently, using proteus-java with Spring Boot causes compilation issues. Spring Boot is pulling in an incompatible version of Guava which overrides the version imported by proteus-java.

## Solution
We need to shade guava in the proteus-java jars.

## Current Workaround
You can force the dependency resolution in Gradle using the following, but it is ugly and not cool of us to ask people to add that to each of their spring-based proteus projects.

```
configurations.all {
    resolutionStrategy {
        dependencySubstitution {
            substitute module('com.google.guava:guava') with module('com.google.guava:guava:22.0')
        }
    }
}
```

**Comment by liqweed** [comment]
Any update on this?

**Comment by gregwhitaker** [comment]
@liqweed This has been fixed in the latest version of Proteus 1.5.3 which will be released later this week.

**Comment by liqweed** [comment]
@gregwhitaker That's great!

I'm trying to integrate Proteus and Guava 22.0 breaks our existing code. Also, I had to temporarily remove errorprone compiler plugin - it's not compatible with this version of Guava as well.

**Comment by liqweed** [comment]
Can this be closed?
